replicaCount: 1
namespace: default

backend:
  image: shreybatra/sample-backend
  service:
    port: 8000

frontend:
  image: shreybatra/sample-frontend
  service:
    port: 5173
    nodePort: 31000

redis:
  image: redis
  service:
    port: 6379
